/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
}

val defaultOauthUrl = "http://localhost:8888/realms/apicurio/protocol/openid-connect/token"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven("https://packages.confluent.io/maven/")
}

dependencies {
    constraints {
        // Define dependency versions as constraints
//        implementation("org.apache.commons:commons-text:1.13.0")
    }
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("6.0.0")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType<JavaExec>().configureEach {
    jvmArgs(
        "--add-opens=java.base/java.lang=ALL-UNNAMED",
        "--add-opens=java.base/java.lang.invoke=ALL-UNNAMED",
        "--add-opens=java.base/java.lang.reflect=ALL-UNNAMED",
        "--add-opens=java.base/java.io=ALL-UNNAMED",
        "--add-opens=java.base/java.nio=ALL-UNNAMED",
        "--add-opens=java.base/java.util=ALL-UNNAMED"
    )

    val allowedUrl = providers.environmentVariable("SR_OIDC_TOKEN_URL")
        .orElse(defaultOauthUrl)
        .getOrNull()
    if (!allowedUrl.isNullOrBlank()) {
        systemProperty("org.apache.kafka.sasl.oauthbearer.allowed.urls", allowedUrl)
    }
}
